language: node_js
node_js:
- stable
before_script:
- npm run init
- npm run public
deploy:
  local_dir: public
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
  edge: true
branch: master